version: "2"
services:
  server:
    image: webapp-server
    ports:
      - "3001:3001"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
      image: mongo
      restart: always
      container_name: mongodb
      volumes:
        - ./data-node:/data/db
      ports:
        - 27017:27017
      command: mongod
      networks:
        - webappnetwork
networks:
    webappnetwork:
      driver: bridge