version: "2"
services:
  client:
    image: webapp-client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - webappnetwork
  api:
    image: webapp-server
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
      image: mongo
      restart: always
      container_name: mongodb
      volumes:
        - ./data-node:/data/db
      ports:
        - 27017:27017
      command: mongod --noauth --smallfiles
      networks:
        - webappnetwork
networks:
    webappnetwork:
      driver: bridge