version: "2"
services:
  server:
    image: shopmet-app
    ports:
      - "3001:3001"
    volumes:
      - ./server:/api
      - /server/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
      image: mongo
      restart: always
      container_name: mongodb
      volumes:
        - ./data-node:/data/db
      ports:
        - 27017:27017
      command: mongod
      networks:
        - webappnetwork
networks:
    webappnetwork:
      driver: bridge