global:
    scrape_interval:     15s
    evaluation_interval: 15s
    external_labels:
      monitor: 'prometheus-monitor'

scrape_configs:
  - job_name: 'Grafana'
    static_configs:
      - targets: [ 'localhost:3000' ]
  - job_name: 'portfolio2'
    scheme: https
    scrape_interval: 5s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['localhost:3001','host.docker.internal:3001']
        labels:
          app: Portfolio2
