global:
    scrape_interval:     15s
    evaluation_interval: 15s
    external_labels:
      monitor: 'prometheus-monitor'

scrape_configs:
  - job_name: 'portfolio2'
    scheme: https
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3001', 'localhost:3001']
        labels:
          app: Portfolio2